### ISSUE TITLE
Fine tunning on KITTI 

### ISSUE THREAD

**Issue by oguzhanilter** [XuJiacong/PIDNet#38]
Hi,

Thank you for sharing this work with the community! 

I am trying to fine-tune the PIDNet on the KITTI dataset by using the 200 images that are provided in [the link ](https://www.cvlibs.net/datasets/kitti/eval_semseg.php?benchmark=semantics2015).  

To this end, I did the following addition/changes: 
1. Resized every image and corresponding semantic GT to the size 1242 x 375, since some images had slightly different sizes. 
2. Created a 'kitti.py' inherited from _base_dataset.py_. The _kitti.py_ is exactly the same as the _cityscapes.py_  except for the class name and the directory path. 
3. Created the _lst_ file in the same format as the lst of cityscapes. 
4. Created a new yaml file exactly the same as the cityscapes' yaml file but changed the IMAGE_SIZE and DATASET name, root, test, and train set paths.

I can run the code with the default parameters and on the cityscapes dataset but I get the following error when I run it on KITTI dataset: 

> ...
>  ../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:145: operator(): block: [262,0,0], thread: [79,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
> ...
> Traceback (most recent call last):
>   File "tools/train.py", line 218, in <module>
>     main()
>   File "tools/train.py", line 182, in main
>     trainloader, optimizer, model, writer_dict)
>   File "/cluster/home/oilter/PIDNet/tools/../utils/function.py", line 43, in train
>     losses, _, acc, loss_list = model(images, labels, bd_gts)
>   File "/cluster/home/oilter/miniconda3/envs/ss/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/cluster/home/oilter/miniconda3/envs/ss/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 168, in forward
>     outputs = self.parallel_apply(replicas, inputs, kwargs)
>   File "/cluster/home/oilter/miniconda3/envs/ss/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 178, in parallel_apply
>     return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
>   File "/cluster/home/oilter/miniconda3/envs/ss/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
>     output.reraise()
>   File "/cluster/home/oilter/miniconda3/envs/ss/lib/python3.7/site-packages/torch/_utils.py", line 461, in reraise
>     raise exception
> RuntimeError: Caught RuntimeError in replica 0 on device 0.
> Original Traceback (most recent call last):
>   File "/cluster/home/oilter/miniconda3/envs/ss/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
>     output = module(*input, **kwargs)
>   File "/cluster/home/oilter/miniconda3/envs/ss/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/cluster/home/oilter/PIDNet/tools/../utils/utils.py", line 49, in forward
>     loss_s = self.sem_loss(outputs[:-1], labels)
>   File "/cluster/home/oilter/miniconda3/envs/ss/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/cluster/home/oilter/PIDNet/tools/../utils/criterion.py", line 93, in forward
>     for (w, x, func) in zip(balance_weights, score, functions)
>   File "/cluster/home/oilter/PIDNet/tools/../utils/criterion.py", line 93, in <listcomp>
>     for (w, x, func) in zip(balance_weights, score, functions)
>   File "/cluster/home/oilter/PIDNet/tools/../utils/criterion.py", line 72, in _ohem_forward
>     pred, ind = pred.contiguous().view(-1,)[mask].contiguous().sort()
> RuntimeError: CUDA error: device-side assert triggered
> CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
> For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

Any help would be highly appreciated.

**Comment by oguzhanilter** [comment]
The issue was in resizing. While resizing the label image I was not considering the interpolation, which creates some ids which cause 'out of bound'. 
I used cropping instead of resizing.

**Comment by kingskymoon** [comment]
> The issue was in resizing. While resizing the label image I was not considering the interpolation, which creates some ids which cause 'out of bound'. I used cropping instead of resizing.
Hello, I am currently working on something similar. Can you share the modified kitti code? Thank you for your sharing~
