### ISSUE TITLE
训练出错

### ISSUE THREAD

**Issue by piong2333** [XuJiacong/PIDNet#40]
训练一小会之后就出错停止训练，过程数据如下，请问是什么原因呀
![image](https://user-images.githubusercontent.com/53041111/216530128-16c47ae3-3e7e-42b4-94a7-cdf15042aa11.png)

**Comment by JOP-Lee** [comment]
@piong2333 请问你这个怎么跑起来的，pytorch版本是多少呀，我这总提示CUDA error
<img width="765" alt="1675580328573" src="https://user-images.githubusercontent.com/24960306/216806018-89339e89-5b3c-4d61-90ed-09d4ce8ad5d0.png">

**Comment by piong2333** [comment]
> @piong2333 请问你这个怎么跑起来的，pytorch版本是多少呀，我这总提示CUDA error <img alt="1675580328573" width="765" src="https://user-images.githubusercontent.com/24960306/216806018-89339e89-5b3c-4d61-90ed-09d4ce8ad5d0.png">

你有几个gpu呀，我电脑只有一个gpu，改了这几个好像j就跑起来了
![image](https://user-images.githubusercontent.com/53041111/216806457-33714591-54dd-4e68-b88d-402fee47e223.png)
![image](https://user-images.githubusercontent.com/53041111/216806504-aee5be58-58fe-4578-8331-374bdb8b07e7.png)

**Comment by JOP-Lee** [comment]
> > @piong2333 请问你这个怎么跑起来的，pytorch版本是多少呀，我这总提示CUDA error <img alt="1675580328573" width="765" src="https://user-images.githubusercontent.com/24960306/216806018-89339e89-5b3c-4d61-90ed-09d4ce8ad5d0.png">
> 
> 你有几个gpu呀，我电脑只有一个gpu，改了这几个好像j就跑起来了 ![image](https://user-images.githubusercontent.com/53041111/216806457-33714591-54dd-4e68-b88d-402fee47e223.png) ![image](https://user-images.githubusercontent.com/53041111/216806504-aee5be58-58fe-4578-8331-374bdb8b07e7.png)

4块，改了还是这个错。我跑的是cityscape那个视频序列的，不知道是不是这个模型预测出来的结果，不能当作GT训练

**Comment by ShubhamAbhayDeshpande** [comment]
Hello,

I am facing the same error. Can someone tell me exactly what to do? I tried to translate the above answer, and also tried ``` model = model.cuda()``` this did not work for me. The screen shot of my error is as shown below. And, the details about my graphics card are also shown below in image. 

*Error message*

![image](https://user-images.githubusercontent.com/106657733/229918029-6323210b-d778-4e18-920b-10e761ac3c4d.png)


*Graphics card and CUDA details*

![image](https://user-images.githubusercontent.com/106657733/229918201-38c2c8b6-9100-40c1-9467-f7c2ecb32efb.png)

**Comment by piong2333** [comment]
> 

Sorry, I couldn't run this code and ended up giving up. I didn't quite understand the error and couldn't help you solve it. QAQ

**Comment by piong2333** [comment]
> 

Sorry, I couldn't run this code and ended up giving up. I didn't quite understand the error and couldn't help you solve it. QAQ

**Comment by piong2333** [comment]
> Hello,
> 
> I am facing the same error. Can someone tell me exactly what to do? I tried to translate the above answer, and also tried ` model = model.cuda()` this did not work for me. The screen shot of my error is as shown below. And, the details about my graphics card are also shown below in image.
> 
> _Error message_
> 
> ![image](https://user-images.githubusercontent.com/106657733/229918029-6323210b-d778-4e18-920b-10e761ac3c4d.png)
> 
> _Graphics card and CUDA details_
> 
> ![image](https://user-images.githubusercontent.com/106657733/229918201-38c2c8b6-9100-40c1-9467-f7c2ecb32efb.png)

Sorry, I couldn't run this code and ended up giving up. I didn't quite understand the error and couldn't help you solve it. QAQ

**Comment by ShubhamAbhayDeshpande** [comment]
@piong2333 and @JOP-Lee is it possible to use this model purely on CPU cores? I think the error above are caused because insufficient space on GPU (especially when we are using a single GPU).

**Comment by kongbai-account** [comment]
有人遇到这个问题吗，我用cityscapes就能训练完毕，但用自己的数据集就报这个错误
![image](https://github.com/XuJiacong/PIDNet/assets/63712094/731dacd2-d785-4f38-80f9-50b048d51a4a)

**Comment by Zjm33** [comment]
> 有人遇到这个问题吗，我用cityscapes就能训练完毕，但用自己的数据集就报这个错误 Has anyone encountered this problem? I can train with cityscapes, but this error is reported using my own dataset ![image](https://user-images.githubusercontent.com/63712094/257677731-731dacd2-d785-4f38-80f9-50b048d51a4a.png)

请问一下这个问题你解决了吗

**Comment by Lvxuelong** [comment]
> 训练一小会之后就出错停止训练，过程数据如下，请问是什么原因呀 ![图像](https://user-images.githubusercontent.com/53041111/216530128-16c47ae3-3e7e-42b4-94a7-cdf15042aa11.png)

你好，请问你的这个问题解决了吗？

**Comment by Lv595** [comment]
> 训练一小会之后就出错停止训练，过程数据如下，请问是什么原因呀 ![图像](https://user-images.githubusercontent.com/53041111/216530128-16c47ae3-3e7e-42b4-94a7-cdf15042aa11.png)

你好，请问你的这个问题解决了吗？

**Comment by kongbai-account** [comment]
> > 训练一小会之后就出错停止训练，过程数据如下，请问是什么原因呀 ![图像](https://user-images.githubusercontent.com/53041111/216530128-16c47ae3-3e7e-42b4-94a7-cdf15042aa11.png)
> 
> 你好，请问你的这个问题解决了吗？

解决了，issue#65

**Comment by piong2333** [comment]
> > 训练一小会之后就出错停止训练，过程数据如下，请问是什么原因呀 ![图像](https://user-images.githubusercontent.com/53041111/216530128-16c47ae3-3e7e-42b4-94a7-cdf15042aa11.png)
> 
> 你好，请问你的这个问题解决了吗？

没有解决，已经没有进行这个方面的研究了QAQ

**Comment by Lv595** [comment]
> > > 训练一小会之后就出错停止训练，过程数据如下，请问是什么原因呀 ![图像](https://user-images.githubusercontent.com/53041111/216530128-16c47ae3-3e7e-42b4-94a7-cdf15042aa11.png)
> > 
> > 
> > 你好，请问你的这个问题解决了吗？
> 
> 没有解决，已经没有进行这个方面的研究了QAQ

谢谢你的回复，我已解决问题。

**Comment by YUE-GOOD** [comment]
> > > > 训练一小会之后就出错停止训练，过程数据如下，请问是什么原因呀 ![图像](https://user-images.githubusercontent.com/53041111/216530128-16c47ae3-3e7e-42b4-94a7-cdf15042aa11.png)
> > > 
> > > 
> > > 你好，请问你的这个问题解决了吗？
> > 
> > 
> > 没有解决，已经没有进行这个方面的研究了QAQ
> 
> 谢谢你的回复，我已解决问题。

你好，这个要怎么解决？我也遇到了（哭死）

**Comment by AAAdecade** [comment]
> > > > > 训练一小会之后就出错停止训练，过程数据如下，请问是什么原因呀![图像](https://user-images.githubusercontent.com/53041111/216530128-16c47ae3-3e7e-42b4-94a7-cdf15042aa11.png)
> > > > 
> > > > 
> > > > 你好，请问你的这个问题解决了吗？
> > > 
> > > 
> > > 没有解决，已经没有进行这个方面的研究了QAQ
> > 
> > 
> > 谢谢你的回复，我已解决问题。
> 
> 你好，这个要怎么解决？我也遇到了（哭死）

您好！我也遇到了相同的问题。请问您解决了吗
![clipboard-image-1719913128](https://github.com/XuJiacong/PIDNet/assets/145337236/34a08031-96bb-40be-ae2a-92c5caa05880)

**Comment by 085410** [comment]
> > > > 训练一小会之后就出错停止训练，过程数据如下，请问是什么原因呀 ![图像](https://user-images.githubusercontent.com/53041111/216530128-16c47ae3-3e7e-42b4-94a7-cdf15042aa11.png)
> > > 
> > > 
> > > 你好，请问你的这个问题解决了吗？
> > 
> > 
> > 没有解决，已经没有进行这个方面的研究了QAQ
> 
> 谢谢你的回复，我已解决问题。

你好，请问你解决了吗？我用的就是CityScapes数据集进行的训练，数据集没有改动过，但还是发生了该图错误

**Comment by lazy215** [comment]
> > > > 训练一小会之后就出错停止训练，过程数据如下，请问是什么原因呀 ![图像](https://user-images.githubusercontent.com/53041111/216530128-16c47ae3-3e7e-42b4-94a7-cdf15042aa11.png)
> > > 
> > > 
> > > 你好，请问你的这个问题解决了吗？
> > 
> > 
> > 没有解决，已经没有进行这个方面的研究了QAQ
> 
> 谢谢你的回复，我已解决问题。

您好，请问怎么解决的啊
