### ISSUE TITLE
CUDA error while training with custom dataset

### ISSUE THREAD

**Issue by ShubhamAbhayDeshpande** [XuJiacong/PIDNet#47]
Hello,

I am facing the same error. Can someone tell me exactly what to do? I tried to translate the above answer, and also tried  model = model.cuda() this did not work for me. The screen shot of my error is as shown below. And, the details about my graphics card are also shown below in image.

*Error message*

![image](https://user-images.githubusercontent.com/106657733/230177100-e2a49bec-ab96-4854-81f2-0b2591c8b56f.png)

*Graphics card and CUDA details*

![image](https://user-images.githubusercontent.com/106657733/230177296-dcebf841-d710-4bce-982f-6af161a5bc57.png)

I have noticed same issue reported by other users:
https://github.com/XuJiacong/PIDNet/issues/40

Also, @XuJiacong, I have seen that you have mentioned the hardware and framework on which the inference was done. Can you comment about the hardware and other framework requirements used while training? Or simply upload a ```requirements.txt``` file in the new commit to the repo?

**Comment by QiaoShin** [comment]
> Hello,
> 
> I am facing the same error. Can someone tell me exactly what to do? I tried to translate the above answer, and also tried model = model.cuda() this did not work for me. The screen shot of my error is as shown below. And, the details about my graphics card are also shown below in image.
> 
> _Error message_
> 
> ![image](https://user-images.githubusercontent.com/106657733/230177100-e2a49bec-ab96-4854-81f2-0b2591c8b56f.png)
> 
> _Graphics card and CUDA details_
> 
> ![image](https://user-images.githubusercontent.com/106657733/230177296-dcebf841-d710-4bce-982f-6af161a5bc57.png)
> 
> I have noticed same issue reported by other users: #40
> 
> Also, @XuJiacong, I have seen that you have mentioned the hardware and framework on which the inference was done. Can you comment about the hardware and other framework requirements used while training? Or simply upload a `requirements.txt` file in the new commit to the repo?

你们这些问题，都是因为难例ohem_loss。。。 稍微debug一下就知道了，这是难例挖掘的应用时的一个遗留问题，尝试https://github.com/XuJiacong/PIDNet/issues/14#issuecomment-1305105993 我在这个issue中的改动方法，再run一遍，看看是否还会报错

**Comment by ShubhamAbhayDeshpande** [comment]
No I just left the model.

**Comment by sam-sun-2001** [comment]
> > Hello,
> > I am facing the same error. Can someone tell me exactly what to do? I tried to translate the above answer, and also tried model = model.cuda() this did not work for me. The screen shot of my error is as shown below. And, the details about my graphics card are also shown below in image.
> > _Error message_
> > ![image](https://user-images.githubusercontent.com/106657733/230177100-e2a49bec-ab96-4854-81f2-0b2591c8b56f.png)
> > _Graphics card and CUDA details_
> > ![image](https://user-images.githubusercontent.com/106657733/230177296-dcebf841-d710-4bce-982f-6af161a5bc57.png)
> > I have noticed same issue reported by other users: #40
> > Also, @XuJiacong, I have seen that you have mentioned the hardware and framework on which the inference was done. Can you comment about the hardware and other framework requirements used while training? Or simply upload a `requirements.txt` file in the new commit to the repo?
> 
> 你们这些问题，都是因为难例ohem_loss。。。 稍微debug一下就知道了，这是难例挖掘的应用时的一个遗留问题，尝试[#14 (comment)](https://github.com/XuJiacong/PIDNet/issues/14#issuecomment-1305105993) 我在这个issue中的改动方法，再run一遍，看看是否还会报错

还是不行，能不能大佬帮忙一下看看怎么回事？？（衷心希望）

**Comment by sam-sun-2001** [comment]
我解决了这个问题，成功地进行了训练：
OK I solved this problems and train sucessful!!
修改代码：
def _ohem_forward(self, score, target, **kwargs):
        """
        在线样本难例挖掘函数
        """
        """
        score:    outputs[1]     ([3, 19, 1024, 2048])
        target:   [3, 1024, 2048]
        """

        pred = F.softmax(score, dim=1)
        pixel_losses = self.criterion(score, target).contiguous().view(-1)#计算每个像素的损失值 pixel_losses 是一个包含每个像素损失值的一维张量
        #标签里面 没有被忽略的位置，记为mask
        mask = target.contiguous().view(-1) != self.ignore_label
        tmp_target = target.clone()
        tmp_target[tmp_target == 255] = 0
        assert (tmp_target >= 0).all() and (tmp_target < pred.size(1)).all(), "Invalid indices in tmp_target"
        #它比较张量 tmp_target 中的每个元素是否都小于 pred 张量的第二个维度的大小
        #pred size:(3,19,1024,2048)
        #tmp_target=3,1024,2048
        #pred_gather:按照索引拿值
        #pred: 最终预测结果
        pred = pred.gather(1, tmp_target.unsqueeze(1))
        pred, ind = pred.contiguous().view(-1,)[mask].contiguous().sort()
        #pred: 是经过排序后的预测概率值的张量。
        #ind: 是排序后的预测概率值在原始张量中的索引位置的张量。
        min_value = pred[min(self.min_kept, pred.numel() - 1)]
        #确定用于选择难样本的阈值
        threshold = max(min_value, self.thresh)
        pixel_losses = pixel_losses[mask][ind]
        pixel_losses = pixel_losses[pred < threshold]
        #pixel_losses.mean():3.0670037269592285
        return pixel_losses.mean()

除此之外，在trainpy中，在构建OhemCrossEntropy类，并将其作为形参传给FullModel的时候，将ignoreLabel修改成255而不是-1
